### ISSUE TITLE
Support different config ext

### ISSUE THREAD

**Issue by FedorSherbakov** [feathersjs/generator-feathers#470]
Generator fails when app config is in different ext from JSON

```
What kind of service is it? A custom service
? What is the name of the service? password-reset
? Which path should the service be registered on? /password-reset
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'ts' of undefined
    at ServiceGenerator.writing (/Users/eqape/.nvm/versions/node/v10.16.0/lib/node_modules/@feathersjs/cli/node_modules/generator-feathers/generators/service/index.js:167:18)
```

**Comment by daffl** [comment]
This has been fixed in `@feathersjs/cli@4.2.0`. If you are using TypeScript, make sure you add `"types": "lib/"` in your `package.json` for this to work.

**Comment by onomated** [comment]
@daffl Still get the error due to https://github.com/feathersjs/generator-feathers/blob/master/generators/service/index.js#L137

**Comment by daffl** [comment]
Ok, now it should be actually fixed in `@feathersjs/cli@4.2.1`. There might still be some edge cases writing configuration but that would be a different issue.
